// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzyuXIWs9dh30qsJSY_zw0r7tC1D4ur-A',
    appId: '1:334445870318:web:5de4f4e3d92d3ec3e747ff',
    messagingSenderId: '334445870318',
    projectId: 'nutritrack-e48f1',
    authDomain: 'nutritrack-e48f1.firebaseapp.com',
    storageBucket: 'nutritrack-e48f1.firebasestorage.app',
    measurementId: 'G-GPGPWDF8RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqG3OWepF5Q4CuyxaKgeNjbNmxxcSs4cA',
    appId: '1:334445870318:android:4ef7023befb9fdc2e747ff',
    messagingSenderId: '334445870318',
    projectId: 'nutritrack-e48f1',
    storageBucket: 'nutritrack-e48f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3glZS0ijQxMT64T_Ak6vjTGc1KPV3jdU',
    appId: '1:334445870318:ios:292a5a0c45b1e071e747ff',
    messagingSenderId: '334445870318',
    projectId: 'nutritrack-e48f1',
    storageBucket: 'nutritrack-e48f1.firebasestorage.app',
    androidClientId: '334445870318-mfmf3mn9l464bsp2lhdaa6oka2fjrr4g.apps.googleusercontent.com',
    iosClientId: '334445870318-ldcl5d590skl56lqfg2bhendqhad997o.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutritrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3glZS0ijQxMT64T_Ak6vjTGc1KPV3jdU',
    appId: '1:334445870318:ios:292a5a0c45b1e071e747ff',
    messagingSenderId: '334445870318',
    projectId: 'nutritrack-e48f1',
    storageBucket: 'nutritrack-e48f1.firebasestorage.app',
    androidClientId: '334445870318-mfmf3mn9l464bsp2lhdaa6oka2fjrr4g.apps.googleusercontent.com',
    iosClientId: '334445870318-ldcl5d590skl56lqfg2bhendqhad997o.apps.googleusercontent.com',
    iosBundleId: 'com.example.nutritrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzyuXIWs9dh30qsJSY_zw0r7tC1D4ur-A',
    appId: '1:334445870318:web:1d8480924a9e859fe747ff',
    messagingSenderId: '334445870318',
    projectId: 'nutritrack-e48f1',
    authDomain: 'nutritrack-e48f1.firebaseapp.com',
    storageBucket: 'nutritrack-e48f1.firebasestorage.app',
    measurementId: 'G-HN34JXYNGG',
  );
}
